import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Manhas AC Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navItems = [
    {
      name: "Home",
      link: "/",
      // icon: <IconHome className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
    // {
    //   name: "About",
    //   link: "/about",
    //   // icon: <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />,
    // },
    {
      name: "Contact",
      link: "/contact",
      // icon: (
        // <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />
      // ),
    },
  ];
  return (
    <html lang="en" className="scrollbar-thin scrollbar-thumb-blue-500 scrollbar-track-transparent scrollbar-medium scroll-smooth">
      <body className={inter.className}>
        <main style={{overflowX:"hidden",backgroundColor:"#201d1d"}}>
          <FloatingNav navItems={navItems}/>
          {children}
        </main>
      </body>
    </html>
  );
}
